%toDataframeIE

% % % Write data frame of fixations and responses to feed mixed effects analysis
clear all; clc

this_group   = {'Ita-Eng'};
nsubj        = 36; %%%
ntrial       = 12;
nwin_o       = 8;
nwin_p       = 6;

overt       = readtable('overt.csv');
pro         = readtable('pro.csv');

subjecto = strrep(table2cell(overt(:, 'subject')), 'subject', this_group);
subjectp = strrep(table2cell(pro(:, 'subject')), 'subject', this_group);

if isequal(subjecto, subjectp)
    %% fixations 
    
    
    % overt
    r_fixpron1_o = reshape(table2cell(overt(:,'propPronoun_1')), ntrial, nsubj);
    r_fixpron2_o = reshape(table2cell(overt(:,'propPronoun_2')), ntrial, nsubj);
    r_fixverb1_o = reshape(table2cell(overt(:,'propVerb_1')), ntrial, nsubj);
    r_fixverb2_o = reshape(table2cell(overt(:,'propVerb_2')), ntrial, nsubj);
    r_fixadverb1_o = reshape(table2cell(overt(:,'propAdverb_1')), ntrial, nsubj);
    r_fixadverb2_o = reshape(table2cell(overt(:,'propAdverb_2')), ntrial, nsubj);
    r_fixpred1_o = reshape(table2cell(overt(:,'propPredicate_1')), ntrial, nsubj);
    r_fixpred2_o = reshape(table2cell(overt(:,'propPredicate_2')), ntrial, nsubj);
    
    fix_o = [r_fixpron1_o; r_fixpron2_o; r_fixverb1_o; r_fixverb2_o; ...
        r_fixadverb1_o; r_fixadverb2_o; r_fixpred1_o; r_fixpred2_o];
    arc_fix_o = num2cell(rau_score(cell2mat(fix_o)/100));
    
    condition_o = repmat({'overt'}, ntrial*nwin_o, nsubj);
    trial_o = repmat(reshape(table2cell(overt(:,'trial')), ntrial, nsubj), nwin_o, 1);
    
    antecedent = repmat([repmat({'subject'}, ntrial, 1); repmat({'object'}, ntrial, 1)], ...
        nsubj*nwin_o/2, 1);
    win_o = repmat([repmat({'pron'}, ntrial*2, 1); ...
        repmat({'verb'}, ntrial*2, 1); ...
        repmat({'adverb'}, ntrial*2, 1); ...
        repmat({'adj'}, ntrial*2, 1)], nsubj, 1);
    
    overtdf = [reshape(trial_o, nsubj*ntrial*nwin_o, 1)  ...
        reshape(condition_o, nsubj*ntrial*nwin_o, 1)...
        antecedent...
        win_o...
        reshape(fix_o, nsubj*ntrial*nwin_o, 1)...
        reshape(arc_fix_o, nsubj*ntrial*nwin_o, 1)];
    
    % pro
    r_fixverb1_p = reshape(table2cell(pro(:,'propVerb_1')), ntrial, nsubj);
    r_fixverb2_p = reshape(table2cell(pro(:,'propVerb_2')), ntrial, nsubj);
    r_fixadverb1_p = reshape(table2cell(pro(:,'propAdverb_1')), ntrial, nsubj);
    r_fixadverb2_p = reshape(table2cell(pro(:,'propAdverb_2')), ntrial, nsubj);
    r_fixpred1_p = reshape(table2cell(pro(:,'propPredicate_1')), ntrial, nsubj);
    r_fixpred2_p = reshape(table2cell(pro(:,'propPredicate_2')), ntrial, nsubj);
    
    fix_p = [r_fixverb1_p; r_fixverb2_p; ...
        r_fixadverb1_p; r_fixadverb2_p; r_fixpred1_p; r_fixpred2_p];
    arc_fix_p = num2cell(rau_score(cell2mat(fix_p)/100));
    
    condition_p = repmat({'pro'}, ntrial*nwin_p, nsubj);
    trial_p = repmat(reshape(table2cell(pro(:,'trial')), ntrial, nsubj), nwin_p, 1);
    
    antecedent = repmat([repmat({'subject'}, ntrial, 1); repmat({'object'}, ntrial, 1)], ...
        nsubj*nwin_p/2, 1);
    win_p = repmat([ ...
        repmat({'verb'}, ntrial*2, 1); ...
        repmat({'adverb'}, ntrial*2, 1); ...
        repmat({'adj'}, ntrial*2, 1)], nsubj, 1);
    
    prodf = [reshape(trial_p, nsubj*ntrial*nwin_p, 1)  ...
        reshape(condition_p, nsubj*ntrial*nwin_p, 1)...
        antecedent...
        win_p...
        reshape(fix_p, nsubj*ntrial*nwin_p, 1)...
        reshape(arc_fix_p, nsubj*ntrial*nwin_p, 1)];
    
    % all together now
    group = repmat(this_group, ntrial*(nwin_o+nwin_p)*nsubj,1);
    subjectof = reshape(repmat(reshape(subjecto, ntrial,nsubj),nwin_o, 1),...
        ntrial*nwin_o*nsubj, 1);
    subjectpf = reshape(repmat(reshape(subjecto, ntrial,nsubj),nwin_p, 1),...
        ntrial*nwin_p*nsubj, 1);
    subject = [subjectof; subjectpf];    
    df = table([group subject [overtdf; prodf]]);
    df = table2array(df);
    df = table(df(:,1), df(:,2), df(:,3), df(:,4),...
        df(:,5), df(:,6), df(:,7), df(:,8));
    df.Properties.VariableNames = { ...
        'group'...
        'subject'...
        'trial'...
        'condition'....
        'antecedent'....
        'window'...
        'fix_prop'...
        'fix_arc'};
    writetable(df, ['data_fixations_' char(this_group) '.csv'])
    
      
    %% put together responses and RTs
    
    conditionr_p = repmat({'pro'}, length(subjectp), 1);
    conditionr_o = repmat({'overt'}, length(subjectp), 1);
    dfr = [repmat(this_group, length(subjectp)+length(subjectp), 1)...
        [subjecto; subjectp]...
        [pro(:, 'trial'); overt(:, 'trial')]...
        [conditionr_p; conditionr_o]...
        [pro(:, 'response'); overt(:, 'response')]...
        [pro(:, 'RT'); overt(:, 'RT')]];
    dfr.Properties.VariableNames = { ...
        'group'...
        'subject'...
        'trial'...
        'condition'....
        'response'....
        'RT'};
    
    writetable(dfr, ['data_responses_' char(this_group) '.csv'])
    
else display('check your files')
end
